# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38f61212355f7cbe4b3907561f0494e7c04e5b028c5105c105a1db8f3f8d8263b9d722fcbaec8dd3fd0c84f3070b18e44939ec09c9a2f56179fd99ea884c7a1f

test:
  secret_key_base: ac14ed9e2b0b1393bde4f72aef98d678797ea3e11db4fa9da68d972ea95a33bfb54241813420d11bdba78923dba5c865871e8d2aa6b4271f0b9d5522755a5fd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
